"""
Weekly Email Digest Generator
Generates an HTML email summary of the week's ad intelligence.
Can be sent via any email service or printed as a standalone report.
"""
import json
from datetime import datetime
from pathlib import Path

DATA_DIR = Path(__file__).parent.parent / "data"


def generate_weekly_digest() -> str:
    """Generate an HTML email digest of the week's ad intelligence."""
    now = datetime.now()

    # Load latest data
    try:
        history = json.loads((DATA_DIR / "ad_history.json").read_text())
    except Exception:
        history = {}

    try:
        messaging = json.loads((DATA_DIR / "messaging_analysis.json").read_text())
    except Exception:
        messaging = {}

    try:
        gaps = json.loads((DATA_DIR / "messaging_gaps.json").read_text())
    except Exception:
        gaps = {}

    # Compute stats
    total_ads = len(history)
    new_this_week = sum(1 for v in history.values()
                        if v.get("first_seen", "") >= (now.strftime("%Y-%m-%d")[:8] + "01"))
    stopped = sum(1 for v in history.values() if v.get("status") == "stopped")
    active = sum(1 for v in history.values() if v.get("status") == "active")

    # Messaging insights
    msg_dist = messaging.get("messaging_distribution", {})
    trilogy_share = messaging.get("trilogy_share", {})
    top_angles = sorted(msg_dist.items(), key=lambda x: -x[1])[:5]

    # Gaps
    gap_list = gaps.get("gaps", {}).get("gaps", [])

    html = f"""<!DOCTYPE html>
<html>
<head>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #F0F2F5; margin: 0; padding: 20px; }}
  .container {{ max-width: 600px; margin: 0 auto; background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 2px 12px rgba(0,0,0,0.1); }}
  .header {{ background: #1877F2; color: white; padding: 24px; }}
  .header h1 {{ font-size: 20px; margin: 0; }}
  .header p {{ font-size: 13px; opacity: 0.85; margin: 4px 0 0; }}
  .section {{ padding: 20px 24px; border-bottom: 1px solid #E4E6EB; }}
  .section h2 {{ font-size: 16px; color: #1C1E21; margin: 0 0 12px; }}
  .stats {{ display: flex; gap: 12px; }}
  .stat {{ flex: 1; background: #F0F2F5; border-radius: 8px; padding: 12px; text-align: center; }}
  .stat .num {{ font-size: 24px; font-weight: 700; color: #1877F2; }}
  .stat .lbl {{ font-size: 11px; color: #65676B; }}
  .item {{ padding: 8px 0; border-bottom: 1px solid #F0F2F5; font-size: 14px; }}
  .item:last-child {{ border: none; }}
  .gap {{ color: #E4405F; }}
  .strength {{ color: #31A24C; }}
  .cta-btn {{ display: inline-block; background: #1877F2; color: white; padding: 10px 24px; border-radius: 8px; text-decoration: none; font-weight: 600; font-size: 14px; margin-top: 12px; }}
  .footer {{ padding: 16px 24px; text-align: center; color: #8A8D91; font-size: 12px; }}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>TC Ads QA — Weekly Digest</h1>
    <p>Week of {now:%d %B %Y} · Support at Home Intelligence</p>
  </div>

  <div class="section">
    <h2>This Week's Numbers</h2>
    <div class="stats">
      <div class="stat"><div class="num">{active}</div><div class="lbl">Active Ads</div></div>
      <div class="stat"><div class="num">{new_this_week}</div><div class="lbl">New This Week</div></div>
      <div class="stat"><div class="num">{stopped}</div><div class="lbl">Stopped</div></div>
      <div class="stat"><div class="num">{total_ads}</div><div class="lbl">Total Tracked</div></div>
    </div>
  </div>

  <div class="section">
    <h2>Top Messaging Themes in Market</h2>
"""

    for angle, count in top_angles:
        ts = trilogy_share.get(angle, 0)
        label = angle.replace("_", " ").title()
        cls = "strength" if ts >= 50 else "gap" if ts < 20 else ""
        html += f'    <div class="item"><strong>{label}</strong> — {count} ads across market <span class="{cls}">(Trilogy: {ts}%)</span></div>\n'

    html += "  </div>\n"

    if gap_list:
        html += '  <div class="section">\n    <h2>Messaging Gaps to Fill</h2>\n'
        for g in gap_list[:3]:
            label = g["angle"].replace("_", " ").title()
            html += f'    <div class="item gap">⚠ <strong>{label}</strong> — {g["competitor_count"]} competitor ads, 0 Trilogy</div>\n'
        html += "  </div>\n"

    html += f"""
  <div class="section" style="text-align:center;">
    <a href="https://nickltrilogycare.github.io/tc-ads-qa/" class="cta-btn">Open Full Dashboard →</a>
  </div>

  <div class="footer">
    Generated by TC Ads QA Tool · {now:%A %d %B %Y %H:%M}<br>
    Reply to this email with feedback to improve the platform.
  </div>
</div>
</body>
</html>"""

    # Save
    out_path = DATA_DIR.parent / "reports" / f"digest_{now:%Y%m%d}.html"
    out_path.write_text(html)
    print(f"  Digest saved: {out_path}")
    return html


if __name__ == "__main__":
    generate_weekly_digest()
